version: '3.8'
services:
  server:
    build:
      context: .
      target: server_image
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDR=0.0.0.0
      - PORT=8080
      - TIME_ADDITION_MS=2000
      - TIME_SUBTRACTION_MS=2000
      - TIME_MULTIPLICATION_MS=3000
      - TIME_DIVISIONS_MS=3000
    restart: on-failure

  agent:
    build:
      context: .
      target: agent_image
    environment:
      - COMPUTING_POWER=2
    depends_on:
      - server
    restart: on-failure